// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eStat.DAL.Core;

#nullable disable

namespace eStat.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230525080849_added price predictions")]
    partial class addedpricepredictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eStat.DAL.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hyperlink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HyperlinkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationGUID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eStat.DAL.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderProductGUID");

                    b.HasIndex("OrderGUID");

                    b.HasIndex("ProductGUID");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("eStat.DAL.Entities.PriceChange", b =>
                {
                    b.Property<Guid>("PriceChangeGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FromPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ToPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PriceChangeGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("UserProductGUID");

                    b.ToTable("PriceChanges");
                });

            modelBuilder.Entity("eStat.DAL.Entities.PricePrediction", b =>
                {
                    b.Property<Guid>("PricePredictionGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePriceLastMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AverageStockPerRetailerLastMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentAveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentAverageStockPerRetailer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MyAveragePriceLastMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MyCurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MySellsLastMonth")
                        .HasColumnType("int");

                    b.Property<int>("MyStock")
                        .HasColumnType("int");

                    b.Property<int>("NbOfPurchasesLastMonth")
                        .HasColumnType("int");

                    b.Property<int>("NbOfSearchesLastMonth")
                        .HasColumnType("int");

                    b.Property<decimal?>("PredictedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PricePredictionGUID");

                    b.ToTable("PricePredictions");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductGUID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ProductRequest", b =>
                {
                    b.Property<Guid>("ProductRequestGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductRequestGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("ProductRequests");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Purchase", b =>
                {
                    b.Property<Guid>("PurchaseGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("eStat.DAL.Entities.PurchaseProduct", b =>
                {
                    b.Property<Guid>("PurchaseProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("PurchaseGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PurchaseProductGUID");

                    b.HasIndex("PurchaseGUID");

                    b.HasIndex("UserProductGUID");

                    b.ToTable("PurchaseProducts");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Search", b =>
                {
                    b.Property<Guid>("SearchGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SearchGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("ShoppingCartGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingCartGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ShoppingCartProduct", b =>
                {
                    b.Property<Guid>("ShoppingCartProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShoppingCartGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingCartProductGUID");

                    b.HasIndex("ShoppingCartGUID");

                    b.HasIndex("UserProductGUID");

                    b.ToTable("ShoppingCartProducts");
                });

            modelBuilder.Entity("eStat.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Membership")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserGUID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eStat.DAL.Entities.UserProduct", b =>
                {
                    b.Property<Guid>("UserProductGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid?>("ProductGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserProductGUID");

                    b.HasIndex("ProductGUID");

                    b.HasIndex("UserGUID");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Order", b =>
                {
                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserGUID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.OrderProduct", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderGUID");

                    b.HasOne("eStat.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eStat.DAL.Entities.PriceChange", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eStat.DAL.Entities.UserProduct", "UserProduct")
                        .WithMany()
                        .HasForeignKey("UserProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ProductRequest", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Purchase", b =>
                {
                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGUID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.PurchaseProduct", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Purchase", "Purchase")
                        .WithMany("Products")
                        .HasForeignKey("PurchaseGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eStat.DAL.Entities.UserProduct", "UserProduct")
                        .WithMany()
                        .HasForeignKey("UserProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Search", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ShoppingCart", b =>
                {
                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGUID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ShoppingCartProduct", b =>
                {
                    b.HasOne("eStat.DAL.Entities.ShoppingCart", "ShoppingCart")
                        .WithMany("Products")
                        .HasForeignKey("ShoppingCartGUID");

                    b.HasOne("eStat.DAL.Entities.UserProduct", "UserProduct")
                        .WithMany()
                        .HasForeignKey("UserProductGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("eStat.DAL.Entities.UserProduct", b =>
                {
                    b.HasOne("eStat.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductGUID");

                    b.HasOne("eStat.DAL.Entities.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eStat.DAL.Entities.Purchase", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eStat.DAL.Entities.ShoppingCart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eStat.DAL.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
